// Code generated by github.com/efritz/go-mockgen 0.1.0; DO NOT EDIT.
// This file was generated by robots at
// 2019-06-09T21:34:04-05:00
// using the command
// $ go-mockgen -f github.com/go-nacelle/process -i Finalizer -o finalizer.go

package mocks

import process "github.com/go-nacelle/process"

// MockFinalizer is a mock impelementation of the Finalizer interface (from
// the package github.com/go-nacelle/process) used for unit testing.
type MockFinalizer struct {
	// FinalizeFunc is an instance of a mock function object controlling the
	// behavior of the method Finalize.
	FinalizeFunc *FinalizerFinalizeFunc
}

// NewMockFinalizer creates a new mock of the Finalizer interface. All
// methods return zero values for all results, unless overwritten.
func NewMockFinalizer() *MockFinalizer {
	return &MockFinalizer{
		FinalizeFunc: &FinalizerFinalizeFunc{
			defaultHook: func() error {
				return nil
			},
		},
	}
}

// NewMockFinalizerFrom creates a new mock of the MockFinalizer interface.
// All methods delegate to the given implementation, unless overwritten.
func NewMockFinalizerFrom(i process.Finalizer) *MockFinalizer {
	return &MockFinalizer{
		FinalizeFunc: &FinalizerFinalizeFunc{
			defaultHook: i.Finalize,
		},
	}
}

// FinalizerFinalizeFunc describes the behavior when the Finalize method of
// the parent MockFinalizer instance is invoked.
type FinalizerFinalizeFunc struct {
	defaultHook func() error
	hooks       []func() error
	history     []FinalizerFinalizeFuncCall
}

// Finalize delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockFinalizer) Finalize() error {
	r0 := m.FinalizeFunc.nextHook()()
	m.FinalizeFunc.history = append(m.FinalizeFunc.history, FinalizerFinalizeFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Finalize method of
// the parent MockFinalizer instance is invoked and the hook queue is empty.
func (f *FinalizerFinalizeFunc) SetDefaultHook(hook func() error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Finalize method of the parent MockFinalizer instance inovkes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *FinalizerFinalizeFunc) PushHook(hook func() error) {
	f.hooks = append(f.hooks, hook)
}

// SetDefaultReturn calls SetDefaultDefaultHook with a function that returns
// the given values.
func (f *FinalizerFinalizeFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func() error {
		return r0
	})
}

// PushReturn calls PushDefaultHook with a function that returns the given
// values.
func (f *FinalizerFinalizeFunc) PushReturn(r0 error) {
	f.PushHook(func() error {
		return r0
	})
}

func (f *FinalizerFinalizeFunc) nextHook() func() error {
	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

// History returns a sequence of FinalizerFinalizeFuncCall objects
// describing the invocations of this function.
func (f *FinalizerFinalizeFunc) History() []FinalizerFinalizeFuncCall {
	return f.history
}

// FinalizerFinalizeFuncCall is an object that describes an invocation of
// method Finalize on an instance of MockFinalizer.
type FinalizerFinalizeFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c FinalizerFinalizeFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c FinalizerFinalizeFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}
